state_target_trans:
  reset_pose        : [0.45, 0.0, 0.35]
  approach_to_peg   : [0.46, 0.15, 0.3]
  lower_to_peg      : [0.46, 0.15, 0.19]    #0.028
  move_to_hole_above: [0.5, 0.0, 0.33]  #0.063, 0.09
  lower_to_hole     : [0.51, 0.0, 0.221] # 0.226, 0.233(with pad)
  # match_to_hole     : [0.0, 0.0, 0.0165] #0.019 / 0.016
  # insert_to_hole    : [0.0, 0.0, 0.0115]
  # contact           : [0.4, 0.0, 0.165]
  contact_and_move  : [0.4645, -0.024, 0.221] #0.025
  done              : [0.0, 0.0, 0.221]

state_target_ori:
  reset_euler      : [0.0, 0.0, 0.0]
  target_euler      : [0.0, 0.0, 0.0]

state_pose_thres:
  trans_thres: 0.005

control_params:
  pose_limits: [0.30, 0.6, -0.30, 0.30, 0.015, 0.4]
